// log in as Troels
POST https://localhost:7130/auth/login
Content-Type: application/json

{ "Username" : "trmo", "Password" : "onetwo3FOUR" }

### // log in as Jakob
POST https://localhost:7130/auth/login
Content-Type: application/json

{ "Username" : "jknr", "Password" : "password" }

### // allow anonymous
GET https://localhost:7130/test/allowanon

### // must be authorized
GET https://localhost:7130/test/authorized
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI2MDYzNjEyMC1mMDljLTRmY2QtYTg1OS1mYzc4NGI1Zjk4MjMiLCJpYXQiOiIxMi8wOC8yMDIyIDA5OjAwOjE5IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRybW8iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUZWFjaGVyIiwiRGlzcGxheU5hbWUiOiJUcm9lbHMgTW9ydGVuc2VuIiwiRW1haWwiOiJ0cm1vQHZpYS5kayIsIkFnZSI6IjM2IiwiRG9tYWluIjoidmlhIiwiZXhwIjoxNjYwMjk4NDE5LCJpc3MiOiJKV1RBdXRoZW50aWNhdGlvblNlcnZlciIsImF1ZCI6IkpXVFNlcnZpY2VCbGF6b3JXYXNtQ2xpZW50In0.7eYKb9T6Qyxmsi5lvqBYbHlytvOiDN0vb7Bdy5QYe3M7jBujBV6pIS8eKXI0ZJFdjQDa-czIFB3xI9W5Zscwrw


###     // policy mustbevia allowed
GET https://localhost:7130/test/mustbevia
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI0Y2FiOWQ0OS0yYjkwLTRmOTMtYTA4NS04ZmE0OWRmMmU1OTAiLCJpYXQiOiIwNy8wOC8yMDIyIDA5OjQyOjI1IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImprbnIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiRGlzcGxheU5hbWUiOiJKYWtvYiBSYXNtdXNzZW4iLCJFbWFpbCI6Impha29iQGdtYWlsLmNvbSIsIkFnZSI6IjM0IiwiRG9tYWluIjoiZ21haWwiLCJleHAiOjE2NTk4Njg5NDUsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.Fmo7g4cightaPSstq_e_yazW9o4IHEXrmjSLxrq4Ptjq8TV26vRSaYY0wV4Mkv_VGxrKmS4Py2R-R_MXKg4Yew

###    // manual checking MustBeTeacher
GET https://localhost:7130/test/manualcheck
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJkY2JlNTU4Yi1hZjBlLTRmNWUtYWIyNC0wNjBiYzUyZWUxNTkiLCJpYXQiOiIwNy8wOC8yMDIyIDA5OjQ1OjQ4IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImprbnIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiRGlzcGxheU5hbWUiOiJKYWtvYiBSYXNtdXNzZW4iLCJFbWFpbCI6Impha29iQGdtYWlsLmNvbSIsIkFnZSI6IjM0IiwiRG9tYWluIjoiZ21haWwiLCJleHAiOjE2NTk4NjkxNDgsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.3CmYYv_IN9VKHJCLVhyU_y-NNuXO38_TfIoypLdLTTa9QAEbSLdO9h9e2RHIvEIcqJBXScKTLBxwPhihj0obwA





